#ifndef GMP_RENAMES_H
#define GMP_RENAMES_H

// mpz functions
// clang-format off
#define __gmp_asprintf                      bfibe___gmp_asprintf
#define __gmp_asprintf_final                bfibe___gmp_asprintf_final
#define __gmp_asprintf_memory               bfibe___gmp_asprintf_memory
#define __gmp_asprintf_reps                 bfibe___gmp_asprintf_reps
#define __gmp_assert_fail                   bfibe___gmp_assert_fail
#define __gmp_assert_header                 bfibe___gmp_assert_header
#define __gmp_default_allocate              bfibe___gmp_default_allocate
#define __gmp_default_free                  bfibe___gmp_default_free
#define __gmp_default_reallocate            bfibe___gmp_default_reallocate
#define __gmp_divide_by_zero                bfibe___gmp_divide_by_zero
#define __gmp_doprnt                        bfibe___gmp_doprnt
#define __gmp_doprnt_integer                bfibe___gmp_doprnt_integer
#define __gmp_doprnt_mpf2                   bfibe___gmp_doprnt_mpf2
#define __gmp_doscan                        bfibe___gmp_doscan
#define __gmp_exception                     bfibe___gmp_exception
#define __gmp_extract_double                bfibe___gmp_extract_double
#define __gmp_fprintf                       bfibe___gmp_fprintf
#define __gmp_fscanf                        bfibe___gmp_fscanf
#define __gmp_get_memory_functions          bfibe___gmp_get_memory_functions
#define __gmp_init_primesieve               bfibe___gmp_init_primesieve
#define __gmp_invalid_operation             bfibe___gmp_invalid_operation
#define __gmp_mt_recalc_buffer              bfibe___gmp_mt_recalc_buffer
#define __gmp_nextprime                     bfibe___gmp_nextprime
#define __gmp_overflow_in_mpz               bfibe___gmp_overflow_in_mpz
#define __gmp_primesieve                    bfibe___gmp_primesieve
#define __gmp_printf                        bfibe___gmp_printf
#define __gmp_randclear                     bfibe___gmp_randclear
#define __gmp_randclear_mt                  bfibe___gmp_randclear_mt
#define __gmp_randget_mt                    bfibe___gmp_randget_mt
#define __gmp_randinit                      bfibe___gmp_randinit
#define __gmp_randinit_default              bfibe___gmp_randinit_default
#define __gmp_randinit_lc_2exp              bfibe___gmp_randinit_lc_2exp
#define __gmp_randinit_lc_2exp_size         bfibe___gmp_randinit_lc_2exp_size
#define __gmp_randinit_mt                   bfibe___gmp_randinit_mt
#define __gmp_randinit_mt_noseed            bfibe___gmp_randinit_mt_noseed
#define __gmp_randinit_set                  bfibe___gmp_randinit_set
#define __gmp_randiset_mt                   bfibe___gmp_randiset_mt
#define __gmp_randseed                      bfibe___gmp_randseed
#define __gmp_randseed_ui                   bfibe___gmp_randseed_ui
#define __gmp_scanf                         bfibe___gmp_scanf
#define __gmp_set_memory_functions          bfibe___gmp_set_memory_functions
#define __gmp_snprintf                      bfibe___gmp_snprintf
#define __gmp_sprintf                       bfibe___gmp_sprintf
#define __gmp_sqrt_of_negative              bfibe___gmp_sqrt_of_negative
#define __gmp_sscanf                        bfibe___gmp_sscanf
#define __gmp_tmp_reentrant_alloc           bfibe___gmp_tmp_reentrant_alloc
#define __gmp_tmp_reentrant_free            bfibe___gmp_tmp_reentrant_free
#define __gmp_urandomb_ui                   bfibe___gmp_urandomb_ui
#define __gmp_urandomm_ui                   bfibe___gmp_urandomm_ui
#define __gmp_vasprintf                     bfibe___gmp_vasprintf
#define __gmp_vfprintf                      bfibe___gmp_vfprintf
#define __gmp_vfscanf                       bfibe___gmp_vfscanf
#define __gmp_vprintf                       bfibe___gmp_vprintf
#define __gmp_vscanf                        bfibe___gmp_vscanf
#define __gmp_vsnprintf                     bfibe___gmp_vsnprintf
#define __gmp_vsprintf                      bfibe___gmp_vsprintf
#define __gmp_vsscanf                       bfibe___gmp_vsscanf
#define __gmpf_abs                          bfibe___gmpf_abs
#define __gmpf_add                          bfibe___gmpf_add
#define __gmpf_add_ui                       bfibe___gmpf_add_ui
#define __gmpf_ceil                         bfibe___gmpf_ceil
#define __gmpf_clear                        bfibe___gmpf_clear
#define __gmpf_clears                       bfibe___gmpf_clears
#define __gmpf_cmp                          bfibe___gmpf_cmp
#define __gmpf_cmp_d                        bfibe___gmpf_cmp_d
#define __gmpf_cmp_si                       bfibe___gmpf_cmp_si
#define __gmpf_cmp_ui                       bfibe___gmpf_cmp_ui
#define __gmpf_cmp_z                        bfibe___gmpf_cmp_z
#define __gmpf_div                          bfibe___gmpf_div
#define __gmpf_div_2exp                     bfibe___gmpf_div_2exp
#define __gmpf_div_ui                       bfibe___gmpf_div_ui
#define __gmpf_dump                         bfibe___gmpf_dump
#define __gmpf_eq                           bfibe___gmpf_eq
#define __gmpf_fits_sint_p                  bfibe___gmpf_fits_sint_p
#define __gmpf_fits_slong_p                 bfibe___gmpf_fits_slong_p
#define __gmpf_fits_sshort_p                bfibe___gmpf_fits_sshort_p
#define __gmpf_fits_uint_p                  bfibe___gmpf_fits_uint_p
#define __gmpf_fits_ulong_p                 bfibe___gmpf_fits_ulong_p
#define __gmpf_fits_ushort_p                bfibe___gmpf_fits_ushort_p
#define __gmpf_floor                        bfibe___gmpf_floor
#define __gmpf_get_d                        bfibe___gmpf_get_d
#define __gmpf_get_d_2exp                   bfibe___gmpf_get_d_2exp
#define __gmpf_get_default_prec             bfibe___gmpf_get_default_prec
#define __gmpf_get_prec                     bfibe___gmpf_get_prec
#define __gmpf_get_si                       bfibe___gmpf_get_si
#define __gmpf_get_str                      bfibe___gmpf_get_str
#define __gmpf_get_ui                       bfibe___gmpf_get_ui
#define __gmpf_init                         bfibe___gmpf_init
#define __gmpf_init_set                     bfibe___gmpf_init_set
#define __gmpf_init_set_d                   bfibe___gmpf_init_set_d
#define __gmpf_init_set_si                  bfibe___gmpf_init_set_si
#define __gmpf_init_set_str                 bfibe___gmpf_init_set_str
#define __gmpf_init_set_ui                  bfibe___gmpf_init_set_ui
#define __gmpf_init2                        bfibe___gmpf_init2
#define __gmpf_inits                        bfibe___gmpf_inits
#define __gmpf_inp_str                      bfibe___gmpf_inp_str
#define __gmpf_integer_p                    bfibe___gmpf_integer_p
#define __gmpf_mul                          bfibe___gmpf_mul
#define __gmpf_mul_2exp                     bfibe___gmpf_mul_2exp
#define __gmpf_mul_ui                       bfibe___gmpf_mul_ui
#define __gmpf_neg                          bfibe___gmpf_neg
#define __gmpf_out_str                      bfibe___gmpf_out_str
#define __gmpf_pow_ui                       bfibe___gmpf_pow_ui
#define __gmpf_random2                      bfibe___gmpf_random2
#define __gmpf_reldiff                      bfibe___gmpf_reldiff
#define __gmpf_set                          bfibe___gmpf_set
#define __gmpf_set_d                        bfibe___gmpf_set_d
#define __gmpf_set_default_prec             bfibe___gmpf_set_default_prec
#define __gmpf_set_prec                     bfibe___gmpf_set_prec
#define __gmpf_set_prec_raw                 bfibe___gmpf_set_prec_raw
#define __gmpf_set_q                        bfibe___gmpf_set_q
#define __gmpf_set_si                       bfibe___gmpf_set_si
#define __gmpf_set_str                      bfibe___gmpf_set_str
#define __gmpf_set_ui                       bfibe___gmpf_set_ui
#define __gmpf_set_z                        bfibe___gmpf_set_z
#define __gmpf_size                         bfibe___gmpf_size
#define __gmpf_sqrt                         bfibe___gmpf_sqrt
#define __gmpf_sqrt_ui                      bfibe___gmpf_sqrt_ui
#define __gmpf_sub                          bfibe___gmpf_sub
#define __gmpf_sub_ui                       bfibe___gmpf_sub_ui
#define __gmpf_swap                         bfibe___gmpf_swap
#define __gmpf_trunc                        bfibe___gmpf_trunc
#define __gmpf_ui_div                       bfibe___gmpf_ui_div
#define __gmpf_ui_sub                       bfibe___gmpf_ui_sub
#define __gmpf_urandomb                     bfibe___gmpf_urandomb
#define __gmpn_add                          bfibe___gmpn_add
#define __gmpn_add_1                        bfibe___gmpn_add_1
#define __gmpn_add_err1_n                   bfibe___gmpn_add_err1_n
#define __gmpn_add_err2_n                   bfibe___gmpn_add_err2_n
#define __gmpn_add_err3_n                   bfibe___gmpn_add_err3_n
#define __gmpn_add_n                        bfibe___gmpn_add_n
#define __gmpn_add_n_sub_n                  bfibe___gmpn_add_n_sub_n
#define __gmpn_add_nc                       bfibe___gmpn_add_nc
#define __gmpn_addlsh1_n                    bfibe___gmpn_addlsh1_n
#define __gmpn_addlsh2_n                    bfibe___gmpn_addlsh2_n
#define __gmpn_addmul_1                     bfibe___gmpn_addmul_1
#define __gmpn_and_n                        bfibe___gmpn_and_n
#define __gmpn_andn_n                       bfibe___gmpn_andn_n
#define __gmpn_bc_mulmod_bnm1               bfibe___gmpn_bc_mulmod_bnm1
#define __gmpn_bc_set_str                   bfibe___gmpn_bc_set_str
#define __gmpn_bdiv_dbm1c                   bfibe___gmpn_bdiv_dbm1c
#define __gmpn_bdiv_q                       bfibe___gmpn_bdiv_q
#define __gmpn_bdiv_q_1                     bfibe___gmpn_bdiv_q_1
#define __gmpn_bdiv_q_itch                  bfibe___gmpn_bdiv_q_itch
#define __gmpn_bdiv_qr                      bfibe___gmpn_bdiv_qr
#define __gmpn_bdiv_qr_itch                 bfibe___gmpn_bdiv_qr_itch
#define __gmpn_binvert                      bfibe___gmpn_binvert
#define __gmpn_binvert_itch                 bfibe___gmpn_binvert_itch
#define __gmpn_broot                        bfibe___gmpn_broot
#define __gmpn_broot_invm1                  bfibe___gmpn_broot_invm1
#define __gmpn_brootinv                     bfibe___gmpn_brootinv
#define __gmpn_bsqrt                        bfibe___gmpn_bsqrt
#define __gmpn_bsqrtinv                     bfibe___gmpn_bsqrtinv
#define __gmpn_cmp                          bfibe___gmpn_cmp
#define __gmpn_cnd_add_n                    bfibe___gmpn_cnd_add_n
#define __gmpn_cnd_sub_n                    bfibe___gmpn_cnd_sub_n
#define __gmpn_cnd_swap                     bfibe___gmpn_cnd_swap
#define __gmpn_com                          bfibe___gmpn_com
#define __gmpn_compute_powtab               bfibe___gmpn_compute_powtab
#define __gmpn_copyd                        bfibe___gmpn_copyd
#define __gmpn_copyi                        bfibe___gmpn_copyi
#define __gmpn_dc_set_str                   bfibe___gmpn_dc_set_str
#define __gmpn_dcpi1_bdiv_q                 bfibe___gmpn_dcpi1_bdiv_q
#define __gmpn_dcpi1_bdiv_qr                bfibe___gmpn_dcpi1_bdiv_qr
#define __gmpn_dcpi1_bdiv_qr_n              bfibe___gmpn_dcpi1_bdiv_qr_n
#define __gmpn_dcpi1_bdiv_qr_n_itch         bfibe___gmpn_dcpi1_bdiv_qr_n_itch
#define __gmpn_dcpi1_div_q                  bfibe___gmpn_dcpi1_div_q
#define __gmpn_dcpi1_div_qr                 bfibe___gmpn_dcpi1_div_qr
#define __gmpn_dcpi1_div_qr_n               bfibe___gmpn_dcpi1_div_qr_n
#define __gmpn_dcpi1_divappr_q              bfibe___gmpn_dcpi1_divappr_q
#define __gmpn_div_q                        bfibe___gmpn_div_q
#define __gmpn_div_qr_1                     bfibe___gmpn_div_qr_1
#define __gmpn_div_qr_1n_pi1                bfibe___gmpn_div_qr_1n_pi1
#define __gmpn_div_qr_2                     bfibe___gmpn_div_qr_2
#define __gmpn_div_qr_2n_pi1                bfibe___gmpn_div_qr_2n_pi1
#define __gmpn_div_qr_2u_pi1                bfibe___gmpn_div_qr_2u_pi1
#define __gmpn_divexact                     bfibe___gmpn_divexact
#define __gmpn_divexact_1                   bfibe___gmpn_divexact_1
#define __gmpn_divexact_by3                 bfibe___gmpn_divexact_by3
#define __gmpn_divexact_by3c                bfibe___gmpn_divexact_by3c
#define __gmpn_divisible_p                  bfibe___gmpn_divisible_p
#define __gmpn_divmod_1                     bfibe___gmpn_divmod_1
#define __gmpn_divrem                       bfibe___gmpn_divrem
#define __gmpn_divrem_1                     bfibe___gmpn_divrem_1
#define __gmpn_divrem_2                     bfibe___gmpn_divrem_2
#define __gmpn_dump                         bfibe___gmpn_dump
#define __gmpn_fft_best_k                   bfibe___gmpn_fft_best_k
#define __gmpn_fft_next_size                bfibe___gmpn_fft_next_size
#define __gmpn_fib2_ui                      bfibe___gmpn_fib2_ui
#define __gmpn_fib2m                        bfibe___gmpn_fib2m
#define __gmpn_gcd                          bfibe___gmpn_gcd
#define __gmpn_gcd_1                        bfibe___gmpn_gcd_1
#define __gmpn_gcd_11                       bfibe___gmpn_gcd_11
#define __gmpn_gcd_22                       bfibe___gmpn_gcd_22
#define __gmpn_gcd_subdiv_step              bfibe___gmpn_gcd_subdiv_step
#define __gmpn_gcdext                       bfibe___gmpn_gcdext
#define __gmpn_gcdext_1                     bfibe___gmpn_gcdext_1
#define __gmpn_gcdext_hook                  bfibe___gmpn_gcdext_hook
#define __gmpn_gcdext_lehmer_n              bfibe___gmpn_gcdext_lehmer_n
#define __gmpn_get_d                        bfibe___gmpn_get_d
#define __gmpn_get_str                      bfibe___gmpn_get_str
#define __gmpn_hamdist                      bfibe___gmpn_hamdist
#define __gmpn_hgcd                         bfibe___gmpn_hgcd
#define __gmpn_hgcd_appr                    bfibe___gmpn_hgcd_appr
#define __gmpn_hgcd_appr_itch               bfibe___gmpn_hgcd_appr_itch
#define __gmpn_hgcd_itch                    bfibe___gmpn_hgcd_itch
#define __gmpn_hgcd_jacobi                  bfibe___gmpn_hgcd_jacobi
#define __gmpn_hgcd_matrix_adjust           bfibe___gmpn_hgcd_matrix_adjust
#define __gmpn_hgcd_matrix_init             bfibe___gmpn_hgcd_matrix_init
#define __gmpn_hgcd_matrix_mul              bfibe___gmpn_hgcd_matrix_mul
#define __gmpn_hgcd_matrix_mul_1            bfibe___gmpn_hgcd_matrix_mul_1
#define __gmpn_hgcd_matrix_update_q         bfibe___gmpn_hgcd_matrix_update_q
#define __gmpn_hgcd_mul_matrix1_vector      bfibe___gmpn_hgcd_mul_matrix1_vector
#define __gmpn_hgcd_reduce                  bfibe___gmpn_hgcd_reduce
#define __gmpn_hgcd_reduce_itch             bfibe___gmpn_hgcd_reduce_itch
#define __gmpn_hgcd_step                    bfibe___gmpn_hgcd_step
#define __gmpn_hgcd2                        bfibe___gmpn_hgcd2
#define __gmpn_hgcd2_jacobi                 bfibe___gmpn_hgcd2_jacobi
#define __gmpn_invert                       bfibe___gmpn_invert
#define __gmpn_invert_limb                  bfibe___gmpn_invert_limb
#define __gmpn_invertappr                   bfibe___gmpn_invertappr
#define __gmpn_ior_n                        bfibe___gmpn_ior_n
#define __gmpn_iorn_n                       bfibe___gmpn_iorn_n
#define __gmpn_jacobi_2                     bfibe___gmpn_jacobi_2
#define __gmpn_jacobi_base                  bfibe___gmpn_jacobi_base
#define __gmpn_jacobi_n                     bfibe___gmpn_jacobi_n
#define __gmpn_lshift                       bfibe___gmpn_lshift
#define __gmpn_lshiftc                      bfibe___gmpn_lshiftc
#define __gmpn_matrix22_mul                 bfibe___gmpn_matrix22_mul
#define __gmpn_matrix22_mul_itch            bfibe___gmpn_matrix22_mul_itch
#define __gmpn_matrix22_mul1_inverse_vector bfibe___gmpn_matrix22_mul1_inverse_vector
#define __gmpn_mod_1                        bfibe___gmpn_mod_1
#define __gmpn_mod_1_1p                     bfibe___gmpn_mod_1_1p
#define __gmpn_mod_1_1p_cps                 bfibe___gmpn_mod_1_1p_cps
#define __gmpn_mod_1s_2p                    bfibe___gmpn_mod_1s_2p
#define __gmpn_mod_1s_2p_cps                bfibe___gmpn_mod_1s_2p_cps
#define __gmpn_mod_1s_3p                    bfibe___gmpn_mod_1s_3p
#define __gmpn_mod_1s_3p_cps                bfibe___gmpn_mod_1s_3p_cps
#define __gmpn_mod_1s_4p                    bfibe___gmpn_mod_1s_4p
#define __gmpn_mod_1s_4p_cps                bfibe___gmpn_mod_1s_4p_cps
#define __gmpn_mod_34lsub1                  bfibe___gmpn_mod_34lsub1
#define __gmpn_modexact_1c_odd              bfibe___gmpn_modexact_1c_odd
#define __gmpn_mu_bdiv_q                    bfibe___gmpn_mu_bdiv_q
#define __gmpn_mu_bdiv_q_itch               bfibe___gmpn_mu_bdiv_q_itch
#define __gmpn_mu_bdiv_qr                   bfibe___gmpn_mu_bdiv_qr
#define __gmpn_mu_bdiv_qr_itch              bfibe___gmpn_mu_bdiv_qr_itch
#define __gmpn_mu_div_q                     bfibe___gmpn_mu_div_q
#define __gmpn_mu_div_q_itch                bfibe___gmpn_mu_div_q_itch
#define __gmpn_mu_div_qr                    bfibe___gmpn_mu_div_qr
#define __gmpn_mu_div_qr_itch               bfibe___gmpn_mu_div_qr_itch
#define __gmpn_mu_divappr_q                 bfibe___gmpn_mu_divappr_q
#define __gmpn_mu_divappr_q_itch            bfibe___gmpn_mu_divappr_q_itch
#define __gmpn_mul                          bfibe___gmpn_mul
#define __gmpn_mul_1                        bfibe___gmpn_mul_1
#define __gmpn_mul_1c                       bfibe___gmpn_mul_1c
#define __gmpn_mul_basecase                 bfibe___gmpn_mul_basecase
#define __gmpn_mul_fft                      bfibe___gmpn_mul_fft
#define __gmpn_mul_n                        bfibe___gmpn_mul_n
#define __gmpn_mullo_basecase               bfibe___gmpn_mullo_basecase
#define __gmpn_mullo_n                      bfibe___gmpn_mullo_n
#define __gmpn_mulmid                       bfibe___gmpn_mulmid
#define __gmpn_mulmid_basecase              bfibe___gmpn_mulmid_basecase
#define __gmpn_mulmid_n                     bfibe___gmpn_mulmid_n
#define __gmpn_mulmod_bknp1                 bfibe___gmpn_mulmod_bknp1
#define __gmpn_mulmod_bnm1                  bfibe___gmpn_mulmod_bnm1
#define __gmpn_mulmod_bnm1_next_size        bfibe___gmpn_mulmod_bnm1_next_size
#define __gmpn_nand_n                       bfibe___gmpn_nand_n
#define __gmpn_neg                          bfibe___gmpn_neg
#define __gmpn_ni_invertappr                bfibe___gmpn_ni_invertappr
#define __gmpn_nior_n                       bfibe___gmpn_nior_n
#define __gmpn_nussbaumer_mul               bfibe___gmpn_nussbaumer_mul
#define __gmpn_perfect_power_p              bfibe___gmpn_perfect_power_p
#define __gmpn_perfect_square_p             bfibe___gmpn_perfect_square_p
#define __gmpn_pi1_bdiv_q_1                 bfibe___gmpn_pi1_bdiv_q_1
#define __gmpn_popcount                     bfibe___gmpn_popcount
#define __gmpn_pow_1                        bfibe___gmpn_pow_1
#define __gmpn_powlo                        bfibe___gmpn_powlo
#define __gmpn_powm                         bfibe___gmpn_powm
#define __gmpn_preinv_divrem_1              bfibe___gmpn_preinv_divrem_1
#define __gmpn_preinv_mod_1                 bfibe___gmpn_preinv_mod_1
#define __gmpn_preinv_mu_div_qr             bfibe___gmpn_preinv_mu_div_qr
#define __gmpn_preinv_mu_div_qr_itch        bfibe___gmpn_preinv_mu_div_qr_itch
#define __gmpn_random                       bfibe___gmpn_random
#define __gmpn_random2                      bfibe___gmpn_random2
#define __gmpn_redc_1                       bfibe___gmpn_redc_1
#define __gmpn_redc_2                       bfibe___gmpn_redc_2
#define __gmpn_redc_n                       bfibe___gmpn_redc_n
#define __gmpn_remove                       bfibe___gmpn_remove
#define __gmpn_rootrem                      bfibe___gmpn_rootrem
#define __gmpn_rsblsh1_n                    bfibe___gmpn_rsblsh1_n
#define __gmpn_rsblsh2_n                    bfibe___gmpn_rsblsh2_n
#define __gmpn_rsh1add_n                    bfibe___gmpn_rsh1add_n
#define __gmpn_rsh1sub_n                    bfibe___gmpn_rsh1sub_n
#define __gmpn_rshift                       bfibe___gmpn_rshift
#define __gmpn_sbpi1_bdiv_q                 bfibe___gmpn_sbpi1_bdiv_q
#define __gmpn_sbpi1_bdiv_qr                bfibe___gmpn_sbpi1_bdiv_qr
#define __gmpn_sbpi1_bdiv_r                 bfibe___gmpn_sbpi1_bdiv_r
#define __gmpn_sbpi1_div_q                  bfibe___gmpn_sbpi1_div_q
#define __gmpn_sbpi1_div_qr                 bfibe___gmpn_sbpi1_div_qr
#define __gmpn_sbpi1_divappr_q              bfibe___gmpn_sbpi1_divappr_q
#define __gmpn_scan0                        bfibe___gmpn_scan0
#define __gmpn_scan1                        bfibe___gmpn_scan1
#define __gmpn_sec_add_1                    bfibe___gmpn_sec_add_1
#define __gmpn_sec_add_1_itch               bfibe___gmpn_sec_add_1_itch
#define __gmpn_sec_div_qr                   bfibe___gmpn_sec_div_qr
#define __gmpn_sec_div_qr_itch              bfibe___gmpn_sec_div_qr_itch
#define __gmpn_sec_div_r                    bfibe___gmpn_sec_div_r
#define __gmpn_sec_div_r_itch               bfibe___gmpn_sec_div_r_itch
#define __gmpn_sec_invert                   bfibe___gmpn_sec_invert
#define __gmpn_sec_invert_itch              bfibe___gmpn_sec_invert_itch
#define __gmpn_sec_mul                      bfibe___gmpn_sec_mul
#define __gmpn_sec_mul_itch                 bfibe___gmpn_sec_mul_itch
#define __gmpn_sec_pi1_div_qr               bfibe___gmpn_sec_pi1_div_qr
#define __gmpn_sec_pi1_div_r                bfibe___gmpn_sec_pi1_div_r
#define __gmpn_sec_powm                     bfibe___gmpn_sec_powm
#define __gmpn_sec_powm_itch                bfibe___gmpn_sec_powm_itch
#define __gmpn_sec_sqr                      bfibe___gmpn_sec_sqr
#define __gmpn_sec_sqr_itch                 bfibe___gmpn_sec_sqr_itch
#define __gmpn_sec_sub_1                    bfibe___gmpn_sec_sub_1
#define __gmpn_sec_sub_1_itch               bfibe___gmpn_sec_sub_1_itch
#define __gmpn_sec_tabselect                bfibe___gmpn_sec_tabselect
#define __gmpn_set_str                      bfibe___gmpn_set_str
#define __gmpn_sizeinbase                   bfibe___gmpn_sizeinbase
#define __gmpn_sqr                          bfibe___gmpn_sqr
#define __gmpn_sqr_basecase                 bfibe___gmpn_sqr_basecase
#define __gmpn_sqr_diag_addlsh1             bfibe___gmpn_sqr_diag_addlsh1
#define __gmpn_sqrlo                        bfibe___gmpn_sqrlo
#define __gmpn_sqrlo_basecase               bfibe___gmpn_sqrlo_basecase
#define __gmpn_sqrmod_bknp1                 bfibe___gmpn_sqrmod_bknp1
#define __gmpn_sqrmod_bnm1                  bfibe___gmpn_sqrmod_bnm1
#define __gmpn_sqrmod_bnm1_next_size        bfibe___gmpn_sqrmod_bnm1_next_size
#define __gmpn_sqrtrem                      bfibe___gmpn_sqrtrem
#define __gmpn_strongfibo                   bfibe___gmpn_strongfibo
#define __gmpn_sub                          bfibe___gmpn_sub
#define __gmpn_sub_1                        bfibe___gmpn_sub_1
#define __gmpn_sub_err1_n                   bfibe___gmpn_sub_err1_n
#define __gmpn_sub_err2_n                   bfibe___gmpn_sub_err2_n
#define __gmpn_sub_err3_n                   bfibe___gmpn_sub_err3_n
#define __gmpn_sub_n                        bfibe___gmpn_sub_n
#define __gmpn_sub_nc                       bfibe___gmpn_sub_nc
#define __gmpn_sublsh1_n                    bfibe___gmpn_sublsh1_n
#define __gmpn_sublsh2_n                    bfibe___gmpn_sublsh2_n
#define __gmpn_submul_1                     bfibe___gmpn_submul_1
#define __gmpn_tdiv_qr                      bfibe___gmpn_tdiv_qr
#define __gmpn_toom_couple_handling         bfibe___gmpn_toom_couple_handling
#define __gmpn_toom_eval_dgr3_pm1           bfibe___gmpn_toom_eval_dgr3_pm1
#define __gmpn_toom_eval_dgr3_pm2           bfibe___gmpn_toom_eval_dgr3_pm2
#define __gmpn_toom_eval_pm1                bfibe___gmpn_toom_eval_pm1
#define __gmpn_toom_eval_pm2                bfibe___gmpn_toom_eval_pm2
#define __gmpn_toom_eval_pm2exp             bfibe___gmpn_toom_eval_pm2exp
#define __gmpn_toom_eval_pm2rexp            bfibe___gmpn_toom_eval_pm2rexp
#define __gmpn_toom_interpolate_12pts       bfibe___gmpn_toom_interpolate_12pts
#define __gmpn_toom_interpolate_16pts       bfibe___gmpn_toom_interpolate_16pts
#define __gmpn_toom_interpolate_5pts        bfibe___gmpn_toom_interpolate_5pts
#define __gmpn_toom_interpolate_6pts        bfibe___gmpn_toom_interpolate_6pts
#define __gmpn_toom_interpolate_7pts        bfibe___gmpn_toom_interpolate_7pts
#define __gmpn_toom_interpolate_8pts        bfibe___gmpn_toom_interpolate_8pts
#define __gmpn_toom2_sqr                    bfibe___gmpn_toom2_sqr
#define __gmpn_toom22_mul                   bfibe___gmpn_toom22_mul
#define __gmpn_toom3_sqr                    bfibe___gmpn_toom3_sqr
#define __gmpn_toom32_mul                   bfibe___gmpn_toom32_mul
#define __gmpn_toom33_mul                   bfibe___gmpn_toom33_mul
#define __gmpn_toom4_sqr                    bfibe___gmpn_toom4_sqr
#define __gmpn_toom42_mul                   bfibe___gmpn_toom42_mul
#define __gmpn_toom42_mulmid                bfibe___gmpn_toom42_mulmid
#define __gmpn_toom43_mul                   bfibe___gmpn_toom43_mul
#define __gmpn_toom44_mul                   bfibe___gmpn_toom44_mul
#define __gmpn_toom52_mul                   bfibe___gmpn_toom52_mul
#define __gmpn_toom53_mul                   bfibe___gmpn_toom53_mul
#define __gmpn_toom54_mul                   bfibe___gmpn_toom54_mul
#define __gmpn_toom6_sqr                    bfibe___gmpn_toom6_sqr
#define __gmpn_toom62_mul                   bfibe___gmpn_toom62_mul
#define __gmpn_toom63_mul                   bfibe___gmpn_toom63_mul
#define __gmpn_toom6h_mul                   bfibe___gmpn_toom6h_mul
#define __gmpn_toom8_sqr                    bfibe___gmpn_toom8_sqr
#define __gmpn_toom8h_mul                   bfibe___gmpn_toom8h_mul
#define __gmpn_trialdiv                     bfibe___gmpn_trialdiv
#define __gmpn_xnor_n                       bfibe___gmpn_xnor_n
#define __gmpn_xor_n                        bfibe___gmpn_xor_n
#define __gmpn_zero                         bfibe___gmpn_zero
#define __gmpn_zero_p                       bfibe___gmpn_zero_p
#define __gmpq_abs                          bfibe___gmpq_abs
#define __gmpq_add                          bfibe___gmpq_add
#define __gmpq_canonicalize                 bfibe___gmpq_canonicalize
#define __gmpq_clear                        bfibe___gmpq_clear
#define __gmpq_clears                       bfibe___gmpq_clears
#define __gmpq_cmp                          bfibe___gmpq_cmp
#define __gmpq_cmp_si                       bfibe___gmpq_cmp_si
#define __gmpq_cmp_ui                       bfibe___gmpq_cmp_ui
#define __gmpq_cmp_z                        bfibe___gmpq_cmp_z
#define __gmpq_div                          bfibe___gmpq_div
#define __gmpq_div_2exp                     bfibe___gmpq_div_2exp
#define __gmpq_equal                        bfibe___gmpq_equal
#define __gmpq_get_d                        bfibe___gmpq_get_d
#define __gmpq_get_den                      bfibe___gmpq_get_den
#define __gmpq_get_num                      bfibe___gmpq_get_num
#define __gmpq_get_str                      bfibe___gmpq_get_str
#define __gmpq_init                         bfibe___gmpq_init
#define __gmpq_inits                        bfibe___gmpq_inits
#define __gmpq_inp_str                      bfibe___gmpq_inp_str
#define __gmpq_inv                          bfibe___gmpq_inv
#define __gmpq_mul                          bfibe___gmpq_mul
#define __gmpq_mul_2exp                     bfibe___gmpq_mul_2exp
#define __gmpq_neg                          bfibe___gmpq_neg
#define __gmpq_out_str                      bfibe___gmpq_out_str
#define __gmpq_set                          bfibe___gmpq_set
#define __gmpq_set_d                        bfibe___gmpq_set_d
#define __gmpq_set_den                      bfibe___gmpq_set_den
#define __gmpq_set_f                        bfibe___gmpq_set_f
#define __gmpq_set_num                      bfibe___gmpq_set_num
#define __gmpq_set_si                       bfibe___gmpq_set_si
#define __gmpq_set_str                      bfibe___gmpq_set_str
#define __gmpq_set_ui                       bfibe___gmpq_set_ui
#define __gmpq_set_z                        bfibe___gmpq_set_z
#define __gmpq_sub                          bfibe___gmpq_sub
#define __gmpq_swap                         bfibe___gmpq_swap
#define __gmpz_2fac_ui                      bfibe___gmpz_2fac_ui
#define __gmpz_abs                          bfibe___gmpz_abs
#define __gmpz_add                          bfibe___gmpz_add
#define __gmpz_add_ui                       bfibe___gmpz_add_ui
#define __gmpz_addmul                       bfibe___gmpz_addmul
#define __gmpz_addmul_ui                    bfibe___gmpz_addmul_ui
#define __gmpz_and                          bfibe___gmpz_and
#define __gmpz_aorsmul_1                    bfibe___gmpz_aorsmul_1
#define __gmpz_array_init                   bfibe___gmpz_array_init
#define __gmpz_bin_ui                       bfibe___gmpz_bin_ui
#define __gmpz_bin_uiui                     bfibe___gmpz_bin_uiui
#define __gmpz_cdiv_q                       bfibe___gmpz_cdiv_q
#define __gmpz_cdiv_q_2exp                  bfibe___gmpz_cdiv_q_2exp
#define __gmpz_cdiv_q_ui                    bfibe___gmpz_cdiv_q_ui
#define __gmpz_cdiv_qr                      bfibe___gmpz_cdiv_qr
#define __gmpz_cdiv_qr_ui                   bfibe___gmpz_cdiv_qr_ui
#define __gmpz_cdiv_r                       bfibe___gmpz_cdiv_r
#define __gmpz_cdiv_r_2exp                  bfibe___gmpz_cdiv_r_2exp
#define __gmpz_cdiv_r_ui                    bfibe___gmpz_cdiv_r_ui
#define __gmpz_cdiv_ui                      bfibe___gmpz_cdiv_ui
#define __gmpz_clear                        bfibe___gmpz_clear
#define __gmpz_clears                       bfibe___gmpz_clears
#define __gmpz_clrbit                       bfibe___gmpz_clrbit
#define __gmpz_cmp                          bfibe___gmpz_cmp
#define __gmpz_cmp_d                        bfibe___gmpz_cmp_d
#define __gmpz_cmp_si                       bfibe___gmpz_cmp_si
#define __gmpz_cmp_ui                       bfibe___gmpz_cmp_ui
#define __gmpz_cmpabs                       bfibe___gmpz_cmpabs
#define __gmpz_cmpabs_d                     bfibe___gmpz_cmpabs_d
#define __gmpz_cmpabs_ui                    bfibe___gmpz_cmpabs_ui
#define __gmpz_com                          bfibe___gmpz_com
#define __gmpz_combit                       bfibe___gmpz_combit
#define __gmpz_congruent_2exp_p             bfibe___gmpz_congruent_2exp_p
#define __gmpz_congruent_p                  bfibe___gmpz_congruent_p
#define __gmpz_congruent_ui_p               bfibe___gmpz_congruent_ui_p
#define __gmpz_divexact                     bfibe___gmpz_divexact
#define __gmpz_divexact_gcd                 bfibe___gmpz_divexact_gcd
#define __gmpz_divexact_ui                  bfibe___gmpz_divexact_ui
#define __gmpz_divisible_2exp_p             bfibe___gmpz_divisible_2exp_p
#define __gmpz_divisible_p                  bfibe___gmpz_divisible_p
#define __gmpz_divisible_ui_p               bfibe___gmpz_divisible_ui_p
#define __gmpz_dump                         bfibe___gmpz_dump
#define __gmpz_export                       bfibe___gmpz_export
#define __gmpz_fac_ui                       bfibe___gmpz_fac_ui
#define __gmpz_fdiv_q                       bfibe___gmpz_fdiv_q
#define __gmpz_fdiv_q_2exp                  bfibe___gmpz_fdiv_q_2exp
#define __gmpz_fdiv_q_ui                    bfibe___gmpz_fdiv_q_ui
#define __gmpz_fdiv_qr                      bfibe___gmpz_fdiv_qr
#define __gmpz_fdiv_qr_ui                   bfibe___gmpz_fdiv_qr_ui
#define __gmpz_fdiv_r                       bfibe___gmpz_fdiv_r
#define __gmpz_fdiv_r_2exp                  bfibe___gmpz_fdiv_r_2exp
#define __gmpz_fdiv_r_ui                    bfibe___gmpz_fdiv_r_ui
#define __gmpz_fdiv_ui                      bfibe___gmpz_fdiv_ui
#define __gmpz_fib_ui                       bfibe___gmpz_fib_ui
#define __gmpz_fib2_ui                      bfibe___gmpz_fib2_ui
#define __gmpz_fits_sint_p                  bfibe___gmpz_fits_sint_p
#define __gmpz_fits_slong_p                 bfibe___gmpz_fits_slong_p
#define __gmpz_fits_sshort_p                bfibe___gmpz_fits_sshort_p
#define __gmpz_fits_uint_p                  bfibe___gmpz_fits_uint_p
#define __gmpz_fits_ulong_p                 bfibe___gmpz_fits_ulong_p
#define __gmpz_fits_ushort_p                bfibe___gmpz_fits_ushort_p
#define __gmpz_gcd                          bfibe___gmpz_gcd
#define __gmpz_gcd_ui                       bfibe___gmpz_gcd_ui
#define __gmpz_gcdext                       bfibe___gmpz_gcdext
#define __gmpz_get_d                        bfibe___gmpz_get_d
#define __gmpz_get_d_2exp                   bfibe___gmpz_get_d_2exp
#define __gmpz_get_si                       bfibe___gmpz_get_si
#define __gmpz_get_str                      bfibe___gmpz_get_str
#define __gmpz_get_ui                       bfibe___gmpz_get_ui
#define __gmpz_getlimbn                     bfibe___gmpz_getlimbn
#define __gmpz_hamdist                      bfibe___gmpz_hamdist
#define __gmpz_import                       bfibe___gmpz_import
#define __gmpz_init                         bfibe___gmpz_init
#define __gmpz_init_set                     bfibe___gmpz_init_set
#define __gmpz_init_set_d                   bfibe___gmpz_init_set_d
#define __gmpz_init_set_si                  bfibe___gmpz_init_set_si
#define __gmpz_init_set_str                 bfibe___gmpz_init_set_str
#define __gmpz_init_set_ui                  bfibe___gmpz_init_set_ui
#define __gmpz_init2                        bfibe___gmpz_init2
#define __gmpz_inits                        bfibe___gmpz_inits
#define __gmpz_inp_raw                      bfibe___gmpz_inp_raw
#define __gmpz_inp_str                      bfibe___gmpz_inp_str
#define __gmpz_inp_str_nowhite              bfibe___gmpz_inp_str_nowhite
#define mpz_inp_str_nowhite                 bfibe___gmpz_inp_str_nowhite
#define __gmpz_invert                       bfibe___gmpz_invert
#define __gmpz_ior                          bfibe___gmpz_ior
#define __gmpz_jacobi                       bfibe___gmpz_jacobi
#define __gmpz_kronecker_si                 bfibe___gmpz_kronecker_si
#define __gmpz_kronecker_ui                 bfibe___gmpz_kronecker_ui
#define __gmpz_lcm                          bfibe___gmpz_lcm
#define __gmpz_lcm_ui                       bfibe___gmpz_lcm_ui
#define __gmpz_legendre                     bfibe___gmpz_legendre
#define __gmpz_limbs_finish                 bfibe___gmpz_limbs_finish
#define __gmpz_limbs_modify                 bfibe___gmpz_limbs_modify
#define __gmpz_limbs_read                   bfibe___gmpz_limbs_read
#define __gmpz_limbs_write                  bfibe___gmpz_limbs_write
#define __gmpz_lucas_mod                    bfibe___gmpz_lucas_mod
#define __gmpz_lucnum_ui                    bfibe___gmpz_lucnum_ui
#define __gmpz_lucnum2_ui                   bfibe___gmpz_lucnum2_ui
#define __gmpz_mfac_uiui                    bfibe___gmpz_mfac_uiui
#define __gmpz_millerrabin                  bfibe___gmpz_millerrabin
#define __gmpz_mod                          bfibe___gmpz_mod
#define __gmpz_mul                          bfibe___gmpz_mul
#define __gmpz_mul_2exp                     bfibe___gmpz_mul_2exp
#define __gmpz_mul_si                       bfibe___gmpz_mul_si
#define __gmpz_mul_ui                       bfibe___gmpz_mul_ui
#define __gmpz_n_pow_ui                     bfibe___gmpz_n_pow_ui
#define __gmpz_neg                          bfibe___gmpz_neg
#define __gmpz_nextprime                    bfibe___gmpz_nextprime
#define __gmpz_oddfac_1                     bfibe___gmpz_oddfac_1
#define __gmpz_out_raw                      bfibe___gmpz_out_raw
#define __gmpz_out_str                      bfibe___gmpz_out_str
#define __gmpz_perfect_power_p              bfibe___gmpz_perfect_power_p
#define __gmpz_perfect_square_p             bfibe___gmpz_perfect_square_p
#define __gmpz_popcount                     bfibe___gmpz_popcount
#define __gmpz_pow_ui                       bfibe___gmpz_pow_ui
#define __gmpz_powm                         bfibe___gmpz_powm
#define __gmpz_powm_sec                     bfibe___gmpz_powm_sec
#define __gmpz_powm_ui                      bfibe___gmpz_powm_ui
#define __gmpz_prevprime                    bfibe___gmpz_prevprime
#define __gmpz_primorial_ui                 bfibe___gmpz_primorial_ui
#define __gmpz_probab_prime_p               bfibe___gmpz_probab_prime_p
#define __gmpz_prodlimbs                    bfibe___gmpz_prodlimbs
#define __gmpz_random                       bfibe___gmpz_random
#define __gmpz_random2                      bfibe___gmpz_random2
#define __gmpz_realloc                      bfibe___gmpz_realloc
#define __gmpz_realloc2                     bfibe___gmpz_realloc2
#define __gmpz_remove                       bfibe___gmpz_remove
#define __gmpz_roinit_n                     bfibe___gmpz_roinit_n
#define __gmpz_root                         bfibe___gmpz_root
#define __gmpz_rootrem                      bfibe___gmpz_rootrem
#define __gmpz_rrandomb                     bfibe___gmpz_rrandomb
#define __gmpz_scan0                        bfibe___gmpz_scan0
#define __gmpz_scan1                        bfibe___gmpz_scan1
#define __gmpz_set                          bfibe___gmpz_set
#define __gmpz_set_d                        bfibe___gmpz_set_d
#define __gmpz_set_f                        bfibe___gmpz_set_f
#define __gmpz_set_q                        bfibe___gmpz_set_q
#define __gmpz_set_si                       bfibe___gmpz_set_si
#define __gmpz_set_str                      bfibe___gmpz_set_str
#define __gmpz_set_ui                       bfibe___gmpz_set_ui
#define __gmpz_setbit                       bfibe___gmpz_setbit
#define __gmpz_si_kronecker                 bfibe___gmpz_si_kronecker
#define __gmpz_size                         bfibe___gmpz_size
#define __gmpz_sizeinbase                   bfibe___gmpz_sizeinbase
#define __gmpz_sqrt                         bfibe___gmpz_sqrt
#define __gmpz_sqrtrem                      bfibe___gmpz_sqrtrem
#define __gmpz_stronglucas                  bfibe___gmpz_stronglucas
#define __gmpz_sub                          bfibe___gmpz_sub
#define __gmpz_sub_ui                       bfibe___gmpz_sub_ui
#define __gmpz_submul                       bfibe___gmpz_submul
#define __gmpz_submul_ui                    bfibe___gmpz_submul_ui
#define __gmpz_swap                         bfibe___gmpz_swap
#define __gmpz_tdiv_q                       bfibe___gmpz_tdiv_q
#define __gmpz_tdiv_q_2exp                  bfibe___gmpz_tdiv_q_2exp
#define __gmpz_tdiv_q_ui                    bfibe___gmpz_tdiv_q_ui
#define __gmpz_tdiv_qr                      bfibe___gmpz_tdiv_qr
#define __gmpz_tdiv_qr_ui                   bfibe___gmpz_tdiv_qr_ui
#define __gmpz_tdiv_r                       bfibe___gmpz_tdiv_r
#define __gmpz_tdiv_r_2exp                  bfibe___gmpz_tdiv_r_2exp
#define __gmpz_tdiv_r_ui                    bfibe___gmpz_tdiv_r_ui
#define __gmpz_tdiv_ui                      bfibe___gmpz_tdiv_ui
#define __gmpz_tstbit                       bfibe___gmpz_tstbit
#define __gmpz_ui_kronecker                 bfibe___gmpz_ui_kronecker
#define __gmpz_ui_pow_ui                    bfibe___gmpz_ui_pow_ui
#define __gmpz_ui_sub                       bfibe___gmpz_ui_sub
#define __gmpz_urandomb                     bfibe___gmpz_urandomb
#define __gmpz_urandomm                     bfibe___gmpz_urandomm
#define __gmpz_xor                          bfibe___gmpz_xor
// clang-format on

#endif